const EMBER_BOOLEAN = 1;
const EMBER_INTEGER = 2;
const EMBER_BITSTRING = 3;
const EMBER_OCTETSTRING = 4;
const EMBER_NULL = 5;
const EMBER_OBJECTIDENTIFIER = 6;
const EMBER_OBJECTDESCRIPTOR = 7;
const EMBER_EXTERNAL = 8;
const EMBER_REAL = 9;
const EMBER_ENUMERATED = 10;
const EMBER_EMBEDDED = 11;
const EMBER_STRING = 12;
const EMBER_RELATIVE_OID = 13;

const EMBER_SEQUENCE = 0x20 | 16;
const EMBER_SET = 0x20 | 17;

module.exports = {
  EMBER_BOOLEAN,
  EMBER_INTEGER,
  EMBER_BITSTRING,
  EMBER_OCTETSTRING,
  EMBER_NULL,
  EMBER_OBJECTIDENTIFIER,
  EMBER_OBJECTDESCRIPTOR,
  EMBER_EXTERNAL,
  EMBER_REAL,
  EMBER_ENUMERATED,
  EMBER_EMBEDDED,
  EMBER_STRING,
  EMBER_RELATIVE_OID,
  EMBER_SEQUENCE,
  EMBER_SET
};